version: 2

models:
  - name: card_amount_data
    columns:
      - name: MERCHANT_NUMBER_GUID
        tests:
          - not_null          
      - name: CONVERTED_SETTLED_AMOUNT_DIFF
        tests:
          - not_null          
      - name: CARD_TYPE_DIFF
        tests:
          - accepted_values:
              values: ["VI", "MC", "AM"]
          - relationships:
              to: ref('unnested_generic_result')
              field: card_type_credit
