sources:
  - name: wwcredit
    schema: raw
    tables:
      - name: GENERIC_FIELD_VALUE_RESULT
        identifier: GENERIC_FIELD_VALUE_RESULT
        description: This is a iceberg Static table, this table holds the data related to different fields and their values which will be used in different projects without hardcoding any values.  

      - name: SRC_MERCH_DATA
        identifier: SRC_MERCH_DATA
        description: This is a iceberg table, this table holds the data related to merchant.

      - name: SRC_CURRENCY_DATA
        identifier: SRC_CURRENCY_DATA
        description: This is a iceberg table, this table holds the data related to merchant.         

